PRAGMA foreign_keys = ON;

-- UUIDs are generated by the Worker with crypto.randomUUID() and stored as TEXT.
-- UTC timestamps are ISO-8601 TEXT. Booleans are INTEGER 0/1. JSON is validated TEXT.
CREATE TABLE factories (
  id TEXT PRIMARY KEY, name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL CHECK(status IN ('pending','active','passive','suspended')),
  package_status TEXT NOT NULL DEFAULT 'none', bom_explosion_max_depth INTEGER NOT NULL DEFAULT 24 CHECK(bom_explosion_max_depth BETWEEN 1 AND 64),
  approved_by TEXT, approved_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE profiles (
  id TEXT PRIMARY KEY, factory_id TEXT REFERENCES factories(id) ON DELETE CASCADE,
  email TEXT NOT NULL UNIQUE, first_name TEXT NOT NULL DEFAULT '', last_name TEXT NOT NULL DEFAULT '', phone TEXT,
  role TEXT NOT NULL CHECK(role IN ('platform_admin','company_admin','production_user','warehouse_user','shipment_user','viewer')),
  status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','inactive','pending_invite')),
  created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
  CHECK((role='platform_admin' AND factory_id IS NULL) OR (role<>'platform_admin' AND factory_id IS NOT NULL))
);
CREATE TABLE factory_registration_requests (
  id TEXT PRIMARY KEY, requested_factory_name TEXT NOT NULL, requested_slug TEXT NOT NULL,
  applicant_email TEXT NOT NULL, applicant_name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected')),
  created_at TEXT NOT NULL, processed_at TEXT, processed_by TEXT
);
CREATE TABLE factory_subscriptions (
  id TEXT PRIMARY KEY, factory_id TEXT NOT NULL REFERENCES factories(id) ON DELETE CASCADE,
  plan_code TEXT NOT NULL DEFAULT 'none', status TEXT NOT NULL DEFAULT 'inactive', trial_ends_at TEXT,
  created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE permissions (id TEXT PRIMARY KEY, module TEXT NOT NULL, action TEXT NOT NULL, UNIQUE(module,action));
CREATE TABLE role_permissions (
  role TEXT NOT NULL CHECK(role IN ('platform_admin','company_admin','production_user','warehouse_user','shipment_user','viewer')),
  permission_id TEXT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE, PRIMARY KEY(role,permission_id)
);
CREATE TABLE factory_invitations (
  id TEXT PRIMARY KEY, factory_id TEXT NOT NULL REFERENCES factories(id) ON DELETE CASCADE,
  email TEXT NOT NULL, first_name TEXT NOT NULL, last_name TEXT NOT NULL, phone TEXT,
  role TEXT NOT NULL CHECK(role IN ('company_admin','production_user','warehouse_user','shipment_user','viewer')),
  token TEXT NOT NULL UNIQUE, status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','accepted','cancelled')),
  invited_by TEXT NOT NULL, created_at TEXT NOT NULL, expires_at TEXT
);

CREATE TABLE material_categories (
  id TEXT PRIMARY KEY, factory_id TEXT NOT NULL REFERENCES factories(id) ON DELETE RESTRICT,
  name TEXT NOT NULL, code TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(factory_id,code)
);
CREATE TABLE import_batches (
  id TEXT PRIMARY KEY, factory_id TEXT NOT NULL REFERENCES factories(id) ON DELETE RESTRICT,
  file_name TEXT NOT NULL, uploaded_by_user_id TEXT, row_count INTEGER NOT NULL DEFAULT 0,
  success_count INTEGER NOT NULL DEFAULT 0, error_count INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL CHECK(status IN ('işleniyor','tamamlandı','kısmi_hata')), notes TEXT, created_at TEXT NOT NULL
);
CREATE TABLE materials (
  id TEXT PRIMARY KEY, factory_id TEXT NOT NULL REFERENCES factories(id) ON DELETE RESTRICT,
  code TEXT NOT NULL, name TEXT NOT NULL, type TEXT NOT NULL CHECK(type IN ('ham_madde','sarf_malzeme')),
  unit TEXT NOT NULL, min_stock REAL NOT NULL DEFAULT 0, current_stock REAL NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)), category_id TEXT NOT NULL REFERENCES material_categories(id) ON DELETE RESTRICT,
  note TEXT, source_import_batch_id TEXT REFERENCES import_batches(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(factory_id,code)
);
CREATE TABLE locations (
  id TEXT PRIMARY KEY, factory_id TEXT NOT NULL REFERENCES factories(id) ON DELETE RESTRICT,
  name TEXT NOT NULL, code TEXT NOT NULL, type TEXT NOT NULL CHECK(type IN ('depo','üretim_hattı','sevk_bekleme')),
  created_at TEXT NOT NULL, UNIQUE(factory_id,code)
);
CREATE TABLE companies (
  id TEXT PRIMARY KEY, factory_id TEXT NOT NULL REFERENCES factories(id) ON DELETE RESTRICT,
  name TEXT NOT NULL, tax_number TEXT, is_external_manufacturer INTEGER NOT NULL DEFAULT 0 CHECK(is_external_manufacturer IN(0,1)),
  contact_phone TEXT, city TEXT, notes TEXT, created_at TEXT NOT NULL
);
CREATE TABLE departments (
  id TEXT PRIMARY KEY, factory_id TEXT NOT NULL REFERENCES factories(id) ON DELETE RESTRICT,
  name TEXT NOT NULL, code TEXT NOT NULL, notes TEXT, created_at TEXT NOT NULL, UNIQUE(factory_id,code)
);
CREATE TABLE users (
  id TEXT PRIMARY KEY, factory_id TEXT NOT NULL REFERENCES factories(id) ON DELETE RESTRICT,
  full_name TEXT NOT NULL, email TEXT NOT NULL, role TEXT NOT NULL,
  department_id TEXT REFERENCES departments(id) ON DELETE SET NULL, created_at TEXT NOT NULL
);
CREATE TABLE suppliers (
  id TEXT PRIMARY KEY, factory_id TEXT NOT NULL REFERENCES factories(id) ON DELETE RESTRICT,
  name TEXT NOT NULL, contact_person TEXT, phone TEXT, whatsapp TEXT, email TEXT, city TEXT, notes TEXT, created_at TEXT NOT NULL
);
CREATE TABLE assembly_groups (
  id TEXT PRIMARY KEY, factory_id TEXT NOT NULL REFERENCES factories(id) ON DELETE RESTRICT,
  code TEXT NOT NULL, name TEXT NOT NULL, project_reference TEXT,
  import_batch_id TEXT REFERENCES import_batches(id) ON DELETE SET NULL, notes TEXT, created_at TEXT NOT NULL,
  UNIQUE(factory_id,import_batch_id,code)
);
CREATE TABLE parts (
  id TEXT PRIMARY KEY, factory_id TEXT NOT NULL REFERENCES factories(id) ON DELETE RESTRICT,
  import_batch_id TEXT REFERENCES import_batches(id) ON DELETE SET NULL, import_row_id TEXT UNIQUE,
  part_code TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', material_id TEXT REFERENCES materials(id) ON DELETE SET NULL,
  dimensions TEXT, quantity REAL NOT NULL DEFAULT 0, operation TEXT NOT NULL DEFAULT '',
  assigned_company_id TEXT REFERENCES companies(id) ON DELETE SET NULL,
  assembly_group_id TEXT REFERENCES assembly_groups(id) ON DELETE SET NULL,
  type TEXT NOT NULL DEFAULT 'ana_parça' CHECK(type IN ('ana_parça','alt_parça','montaj')), created_at TEXT NOT NULL
);
CREATE TABLE import_rows (
  id TEXT PRIMARY KEY, batch_id TEXT NOT NULL REFERENCES import_batches(id) ON DELETE CASCADE,
  row_index INTEGER NOT NULL, raw_data TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(raw_data)),
  status TEXT NOT NULL CHECK(status IN ('bekliyor','işlendi','hata','yok_sayıldı')), message TEXT,
  linked_part_id TEXT REFERENCES parts(id) ON DELETE SET NULL, created_at TEXT NOT NULL, UNIQUE(batch_id,row_index)
);
CREATE TABLE part_material_requirements (
  id TEXT PRIMARY KEY, part_id TEXT NOT NULL REFERENCES parts(id) ON DELETE CASCADE,
  material_id TEXT NOT NULL REFERENCES materials(id) ON DELETE RESTRICT, quantity_per_unit REAL NOT NULL DEFAULT 1,
  unit TEXT NOT NULL DEFAULT 'adet', note TEXT, created_at TEXT NOT NULL, UNIQUE(part_id,material_id)
);
CREATE TABLE part_route_steps (
  id TEXT PRIMARY KEY, part_id TEXT NOT NULL REFERENCES parts(id) ON DELETE CASCADE,
  step_no INTEGER NOT NULL CHECK(step_no>=1), operation_label TEXT NOT NULL,
  assigned_company_id TEXT REFERENCES companies(id) ON DELETE SET NULL, created_at TEXT NOT NULL, UNIQUE(part_id,step_no)
);
CREATE TABLE part_child_parts (
  id TEXT PRIMARY KEY, parent_part_id TEXT NOT NULL REFERENCES parts(id) ON DELETE CASCADE,
  child_part_id TEXT NOT NULL REFERENCES parts(id) ON DELETE CASCADE, quantity_per_parent REAL NOT NULL DEFAULT 1 CHECK(quantity_per_parent>0),
  unit TEXT NOT NULL DEFAULT 'adet', note TEXT, created_at TEXT NOT NULL,
  CHECK(parent_part_id<>child_part_id), UNIQUE(parent_part_id,child_part_id)
);
CREATE TRIGGER part_child_parts_no_cycle BEFORE INSERT ON part_child_parts
BEGIN
  SELECT CASE WHEN EXISTS(
    WITH RECURSIVE descendants(id) AS (
      SELECT NEW.child_part_id UNION SELECT p.child_part_id FROM part_child_parts p JOIN descendants d ON p.parent_part_id=d.id
    ) SELECT 1 FROM descendants WHERE id=NEW.parent_part_id
  ) THEN RAISE(ABORT,'BOM cycle detected') END;
END;

CREATE TABLE operation_assignments (
  id TEXT PRIMARY KEY, part_id TEXT NOT NULL REFERENCES parts(id) ON DELETE CASCADE, operation_name TEXT NOT NULL,
  assigned_company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT, planned_date TEXT,
  status TEXT NOT NULL DEFAULT 'beklemede' CHECK(status IN ('beklemede','işlemde','tamamlandı')), notes TEXT, created_at TEXT NOT NULL
);
CREATE TABLE products (
  id TEXT PRIMARY KEY, factory_id TEXT NOT NULL REFERENCES factories(id) ON DELETE RESTRICT,
  code TEXT NOT NULL, name TEXT NOT NULL, category TEXT NOT NULL DEFAULT '', unit TEXT NOT NULL DEFAULT 'adet',
  active INTEGER NOT NULL DEFAULT 1 CHECK(active IN(0,1)), note TEXT, created_at TEXT NOT NULL, UNIQUE(factory_id,code)
);
CREATE TABLE product_stock_items (
  id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  current_stock REAL NOT NULL DEFAULT 0, last_production_date TEXT,
  location_id TEXT NOT NULL REFERENCES locations(id) ON DELETE RESTRICT, created_at TEXT NOT NULL, UNIQUE(product_id,location_id)
);
CREATE TABLE production_orders (
  id TEXT PRIMARY KEY, factory_id TEXT NOT NULL REFERENCES factories(id) ON DELETE RESTRICT,
  order_no TEXT NOT NULL, product_id TEXT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  assembly_group_id TEXT REFERENCES assembly_groups(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'taslak' CHECK(status IN ('taslak','planlandı','üretimde','tamamlandı','iptal')),
  quantity_planned REAL NOT NULL DEFAULT 0, quantity_produced REAL NOT NULL DEFAULT 0, scheduled_date TEXT NOT NULL,
  department_id TEXT NOT NULL REFERENCES departments(id) ON DELETE RESTRICT, notes TEXT,
  approved_at TEXT, approved_by TEXT REFERENCES profiles(id) ON DELETE SET NULL, created_at TEXT NOT NULL, UNIQUE(factory_id,order_no)
);
CREATE TABLE production_order_lines (
  id TEXT PRIMARY KEY, production_order_id TEXT NOT NULL REFERENCES production_orders(id) ON DELETE CASCADE,
  material_id TEXT NOT NULL REFERENCES materials(id) ON DELETE RESTRICT, quantity_used REAL NOT NULL DEFAULT 0,
  unit TEXT NOT NULL DEFAULT 'adet', note TEXT, created_at TEXT NOT NULL
);
CREATE TABLE stock_movements (
  id TEXT PRIMARY KEY, factory_id TEXT NOT NULL REFERENCES factories(id) ON DELETE RESTRICT,
  material_id TEXT NOT NULL REFERENCES materials(id) ON DELETE RESTRICT,
  type TEXT NOT NULL CHECK(type IN ('giriş','çıkış','üretimde_kullanım','iade','fire','manuel_düzeltme')),
  quantity REAL NOT NULL, unit TEXT NOT NULL DEFAULT 'adet', occurred_at TEXT NOT NULL,
  location_id TEXT NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
  production_order_id TEXT REFERENCES production_orders(id) ON DELETE SET NULL,
  assembly_group_id TEXT REFERENCES assembly_groups(id) ON DELETE SET NULL, project_reference TEXT, note TEXT,
  supplier_id TEXT REFERENCES suppliers(id) ON DELETE SET NULL, created_at TEXT NOT NULL
);
CREATE TABLE shipments (
  id TEXT PRIMARY KEY, factory_id TEXT NOT NULL REFERENCES factories(id) ON DELETE RESTRICT,
  shipment_number TEXT NOT NULL, shipped_at TEXT NOT NULL, recipient_name TEXT NOT NULL, destination TEXT NOT NULL,
  contact_phone TEXT, contact_email TEXT,
  status TEXT NOT NULL DEFAULT 'taslak' CHECK(status IN ('taslak','hazırlanıyor','yola_çıktı','teslim_edildi','iptal')),
  notes TEXT, created_at TEXT NOT NULL, UNIQUE(factory_id,shipment_number)
);
CREATE TABLE shipment_items (
  id TEXT PRIMARY KEY, shipment_id TEXT NOT NULL REFERENCES shipments(id) ON DELETE CASCADE,
  product_id TEXT NOT NULL REFERENCES products(id) ON DELETE RESTRICT, quantity REAL NOT NULL DEFAULT 0,
  unit TEXT NOT NULL DEFAULT 'adet', stock_movement_ref TEXT, created_at TEXT NOT NULL
);

CREATE INDEX profiles_factory_idx ON profiles(factory_id);
CREATE INDEX materials_factory_idx ON materials(factory_id);
CREATE INDEX parts_factory_idx ON parts(factory_id);
CREATE INDEX parts_group_idx ON parts(assembly_group_id);
CREATE INDEX part_children_parent_idx ON part_child_parts(parent_part_id);
CREATE INDEX part_requirements_part_idx ON part_material_requirements(part_id);
CREATE INDEX production_orders_factory_idx ON production_orders(factory_id);
CREATE INDEX stock_movements_factory_date_idx ON stock_movements(factory_id,occurred_at);
CREATE INDEX import_rows_batch_idx ON import_rows(batch_id);
